quarkus:
  log:
    category:
      "io.kennethmartens":
        level: DEBUG
  application:
    name: ckm-image-service
  http:
    cors: true
    body:
      delete-uploaded-files-on-end: true
  mongodb:
    database: ckm-image
