ckm:
  image:
    filePath: C:\\temp\ckm-images
    service:
      ImageResourceUrl: "http://localhost:8080/api/v1/images/"
quarkus:
  log:
    category:
      "io.kennethmartens":
        level: DEBUG
  application:
    name: ckm-image-service
  http:
    cors: true
    body:
      delete-uploaded-files-on-end: true
  mongodb:
    database: ckm-image

